CREATE TABLE IF NOT EXISTS themes
(
    theme_id                BIGSERIAL PRIMARY KEY,
    primary_color           VARCHAR(20),
    secondary_color         VARCHAR(20),
    accent_color            VARCHAR(20),
    text_color              VARCHAR(20),
    background_color        VARCHAR(20),
    font_family             VARCHAR(100),
    heading_font_family     VARCHAR(100),
    body_font_family        VARCHAR(100),
    logo_url                VARCHAR(500),
    header_image_url        VARCHAR(500),
    footer_logo_url         VARCHAR(500),
    favicon_url             VARCHAR(500),
    button_radius           VARCHAR(20),
    card_radius             VARCHAR(20),
    input_radius            VARCHAR(20),
    button_text_color       VARCHAR(20),
    footer_background_color VARCHAR(20),
    footer_text_color       VARCHAR(20),
    success_color           VARCHAR(20),
    error_color             VARCHAR(20),
    warning_color           VARCHAR(20),
    info_color              VARCHAR(20),
    hover_color             VARCHAR(20),
    active_color            VARCHAR(20),
    box_shadow              VARCHAR(100),
    card_shadow             VARCHAR(100),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);